spring:
  application:
    name: service-provider
  profiles:
    active: provider2
  thymeleaf:
    prefix: classpath:/templates/
  #Redis Configuration
  redis:
    host: hyperledger.hku.hk
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

