server:
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: abcd1234
    key-store-type: PKCS12
    key-alias: tomcat
eureka:
  client:
    serviceUrl:
      defaultZone: http://hyperledger.hku.hk:8761/eureka/